name: nice_water
description: "A Nice water"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  awesome_dialog: ^3.2.0
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.15.8
  dio: ^5.4.1
  dropdown_search2: ^1.0.2
  firebase_auth: ^4.17.8
  firebase_core: ^2.27.0
  firebase_storage: ^11.6.9
  flashy_tab_bar2: ^0.0.10
  flutter_svg: ^2.0.10+1
  line_awesome_flutter: ^2.0.0
  geolocator: ^11.0.0
  google_fonts: 6.1.0
  image_picker: ^1.0.7
  intl: ^0.19.0
  permission_handler: ^11.3.0
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  string_validator: ^1.0.2
  timeago: ^3.6.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10
  flutter_zoom_drawer: ^3.2.0
  flutter_map: any
  latlong2: ^0.9.0
  flutter_map_marker_cluster: ^1.3.5
  flutter_map_supercluster: ^5.0.0-dev.1
  maps_launcher: ^2.2.1
  easy_tooltip: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/logos/
    - assets/svgs/

flutter_native_splash:
  image: assets/logos/splash.png
  color: "#ffffff"
  web_image_mode: center
  android_gravity: center
  ios_content_mode: center
# flutter pub run flutter_native_splash:create
flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logos/logo.png"
  adaptive_icon_background: "#ffffff"
# flutter pub run flutter_launcher_icons:main
